image: ruby:3.0.0
# Liquid 4 与 Ruby 3.2 不兼容。https://github.com/Shopify/liquid/issues/1625#issuecomment-1254061820

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - gem install bundler
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - main

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - main
