# Site
name: "Prompts Push"
title: "Prompts Push"
description: "Hot Prompts, collect beautiful AI paintings and excellent prompts."
description_zh: "提示词小仓库，收集漂亮的AI画作和优秀提示词。"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
url: "https://pinwua.pub"
# google_analytics: 'UA-xxxxxxxx-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
# email: wowthemesnet@gmail.com

# Authors
authors:
  pinwua:
    name: pinwua
    display_name: PinWuA
    avatar: 'assets/images/avatar.webp'
    email: 
    web: https://pinwua.pub/
    twitter: https://twitter.com/wowthemesnet
    description: "Love this magical universe."
  none:
    name: none
    display_name: Guest
    avatar: 'assets/images/avatar-guest.webp'
    email: 
    web: https://pinwua.pub/?s=authors_Guest
    twitter: 
    description: "We never know what will happen next!"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 3
paginate_path: /page/:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

# Themes

# Navigation
# nav
#  - Get Memoirs: https://bootstrapstarter.com/jekyll-theme-memoirs/
#  - Contact: /contact
#  - Contributors: /authors